### ISSUE TITLE
Package não encontrado em nenhum registro FHIR

### ISSUE THREAD

**Issue by kyriosdata** [nogueiralegacy/rnds#4]
Ao construir ig em build.fhir.org, por exemplo, https://build.fhir.org/ig/kyriosdata/farol/branches/__default/failure/build.log, tem-se a falha abaixo:

```
Sushi: info  Checking /home/fhiruser/.fhir/packages for rnds.ajustes#0.0.1...                        (00:00.001 / 00:11.012, 97Mb)
Sushi: info  Did not find rnds.ajustes#0.0.1 in /home/fhiruser/.fhir/packages.                       (00:00.712 / 00:11.725, 97Mb)
Sushi: info  Downloading rnds.ajustes#0.0.1... https://packages.fhir.org/rnds.ajustes/0.0.1          (00:00.000 / 00:11.725, 97Mb)
Sushi: info  Downloading rnds.ajustes#0.0.1... https://packages2.fhir.org/packages/rnds.ajustes/0.0.1 (00:00.459 / 00:12.185, 97Mb)
Sushi: error Failed to load rnds.ajustes#0.0.1: The package rnds.ajustes#0.0.1 could not be loaded locally or from the FHIR package registry. (00:00.181 / 00:12.366, 97Mb)
```

Para eliminar este erro é necessário gerar o package e fazer o registro correspondente em FHIR Package Registry.
Desta forma, qualquer projeto que faça referência ao package aqui produzido poderá ser encontrado e utilizado usando o ecossistema FHIR.

**Comment by nogueiralegacy** [comment]
O package foi registrado no serviço oficial FHIR Package Registry pelo Murílo Luz.
[br.ufg.cgis.rnds-lite](https://registry.fhir.org/package/br.ufg.cgis.rnds-lite%7C0.0.1)
