### ISSUE TITLE
Validador via linha de comandos (validator_cli) aparentemente divergente de validação via $validate

### ISSUE THREAD

**Issue by kyriosdata** [nogueiralegacy/rnds#8]
Ao realizar a validação de um elemento do tipo **code** com binding para ValueSet definido por códigos em pelo menos duas instâncias de CodeSystem, o valiador via linha de comandos resulta em erro atribuído à instância validada, enquanto a validação usando o servidor hapifhir não indica a presença de erro. Se isto ocorre, de fato, então não é um erro do validador?

**Comment by nogueiralegacy** [comment]
# Origem da situação
O ValueSet http://hl7.org/fhir/ValueSet/parent-relationship-codes e uma vinculação desse ValueSet para o tipo "code"
# Análise da situação
Quando é feito um biding para o tipo "code" e o ValueSet ao qual foi realizado essa vinculação inclui o mesmo CodeSystem duas vezes o validador via linha de comandos gera um erro e o validador do servidor HAPI FHIR via operação $validate não gera o erro.

# Artefatos usados para o experimento
[perfil.json](https://github.com/nogueiralegacy/rnds/files/13994734/perfil.json)
[instancia.json](https://github.com/nogueiralegacy/rnds/files/13994735/instancia.json)

# Resultados da validação
[response-jpaserver.txt](https://github.com/nogueiralegacy/rnds/files/13994747/response-jpaserver.txt)
[response-validador-cli.txt](https://github.com/nogueiralegacy/rnds/files/13994750/response-validador-cli.txt)

# Conclusão
Tem uma divergencia entre a validação via CLI e via operação $validate para esse caso específico.
